### ISSUE TITLE
Прикольная идея, но нету инструкции

### ISSUE THREAD

**Issue by mishailovic** [gil9red/telegram__url2image_bot#1]
На днях хотел запустить у себя бота, так и не разобрался как. Была беда с недостающим модулем api телеграма, установил вручную, теперь просит qtwebkit, а в pip'e его нету. 
Если не сложно, сделай инструкцию для чайников. Заранее спасибо!

**Comment by gil9red** [comment]
Добрый день!
Мне (win10, python3.7) установка через `pip install pyqt4` не помогла.

Гугление привело к https://stackoverflow.com/a/22651895/5909792, а тот на сайт с сборками модулей: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4

Скачал **.whl** и установил:
```
C:\Users\ipetrash\Downloads> pip install PyQt4-4.11.4-cp37-cp37m-win_amd64.whl
Processing c:\users\ipetrash\downloads\pyqt4-4.11.4-cp37-cp37m-win_amd64.whl
Installing collected packages: PyQt4
Successfully installed PyQt4-4.11.4
```

Запуск кода прошел удачно:
https://github.com/gil9red/telegram__url2image_bot/blob/41ed147aaa34eda38a330402f6333daa5ec157c5/url2image.py

А так, поддержкой репозиториев не занимаюсь :)
Кст, этот бот мне кажется, не так интересен как эти двое:
 * https://github.com/gil9red/telegram__random_bashim_bot
 * https://github.com/gil9red/SimplePyScripts/tree/23cf9db8e409b280b0bd6d2873888269e0864c08/telegram_bot__image_process_bot

Успехов :)
